### ISSUE TITLE
Parameter validation interface 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nf-validation#1]
The aim of this project is to define a common interface for Nextflow pipeline parameters validation based on the nf-core JSON schema that can be applied to any pipeline without the need to programmatically apply it in the pipeline code. 

In the current validation, method signature takes the `params` map the JSON schema file and return an array on invalid params. 
   
https://github.com/nextflow-io/nf-validation/blob/7423ffa364cba9fee3b4137aa344b6745770fb7d/src/main/nextflow/validation/NfcoreSchema.groovy#L19

@KevinMenden @ewels  How are you using the returned array?

**Comment by KevinMenden** [comment]
First we use the `validateParameters` function to get the array like so:

```
def json_schema = "$baseDir/nextflow_schema.json"
def unexpectedParams = []
if (params.validate_params) {
    unexpectedParams = NfcoreSchema.validateParameters(params, json_schema, log)
}
``` 

And then we simply log the array if the pipeline fails:

```
workflow.onError {
    // Print unexpected parameters
    for (p in unexpectedParams) {
        log.warn "Unexpected parameter: ${p}"
    }
}
```

That's all there is to it. So nothing fancy at all 👍

**Comment by pditommaso** [comment]
I see. Then I think it's a matter of having that method throwing an exception and then NF will do the rest. Let me draft something.

**Comment by ewels** [comment]
Umm, it doesn’t return an array? It exits:

https://github.com/nextflow-io/nf-validation/blob/7423ffa364cba9fee3b4137aa344b6745770fb7d/src/main/nextflow/validation/NfcoreSchema.groovy#L153

**Comment by KevinMenden** [comment]
Isn't that code only executed when the validation fails or when a code parameter is specified? If none of that happens the list of unexpected params should still be returned.

Maybe good to clarify that the array is not of invalid params, but just of unexpected ones. As Phil said when the validation properly fails then the code exits.

**Comment by ewels** [comment]
Yes exactly, sorry I was going on this:

> return an array on invalid params.

Could be interpreted either way I guess :) I was assuming that @pditommaso meant that they were invalid according to the schema..

**Comment by pditommaso** [comment]
Got it. Unexpected params are printed. Invalid ones cause the termination.

**Comment by ewels** [comment]
I suspect that unexpected params will happen a _lot_, given that they can often be used for cluster config setups and all sorts. So yeah, we're only printing them if there is a schema validation error or if the pipeline run has an error.

**Comment by ewels** [comment]
Note also our nasty  hack to allow some parameters to be absent from the schema without generating a warning, so that users can add their own params if they use them like this, to avoid getting warnings about them:

https://github.com/nextflow-io/nf-validation/blob/7423ffa364cba9fee3b4137aa344b6745770fb7d/src/main/nextflow/validation/NfcoreSchema.groovy#L113

**Comment by ewels** [comment]
...time for a config `schema {}` config scope..?! 😆

**Comment by pditommaso** [comment]
> Note also our nasty hack to allow some parameters

I just ran into it!


> ...time for a config schema {} config scope.

😱

**Comment by pditommaso** [comment]
Green! https://github.com/nextflow-io/nf-validation/actions/runs/582625461 🎉

**Comment by pditommaso** [comment]
Ok, I've added some boilerplate required by the plugin system, but the central class remain the same 

https://github.com/nextflow-io/nf-validation/blob/663364bccca698afdfdadc2c09be50bed749164e/plugins/validation/src/main/nextflow/validation/SchemaValidator.groovy


In the following days, I would like to added some unit tests to validate the validator .. similar to this one 

https://github.com/nextflow-io/nf-validation/blob/663364bccca698afdfdadc2c09be50bed749164e/plugins/validation/src/test/nextflow/validation/SchemaValidatorTest.groovy#L11-L21

**Comment by KevinMenden** [comment]
Awesome :) 
I will look a bit into the `cleanParameter` function which is annoying and I hope we can get rid of. We just needed this to convert Nextflow objects back to String to allow validation with the Schema. We are probably converting them to these objects in the first place (`check_max`) function, so hopefully we can omit this function.

**Comment by pditommaso** [comment]
I've refactored the validation class a bit to make it more reusable. My understanding is that you want to distinguish between errors and warning, therefore the `SchemaValidator` when invoked collects them in these two attributes instead of abruptly stopping the execution.  

https://github.com/nextflow-io/nf-validation/blob/abe5287b4870bd3362c86c46ba4ba0e1d96573ec/plugins/validation/src/main/nextflow/validation/SchemaValidator.groovy#L83-L84

By doing so this component can be reused for different purposes. The invoking class will take care to print the error/warning messages and stop the execution. 

If you could contribute some tests for the validation conditions you want to capture that would help a lot. 

https://github.com/nextflow-io/nf-validation/blob/abe5287b4870bd3362c86c46ba4ba0e1d96573ec/plugins/validation/src/test/nextflow/validation/SchemaValidatorTest.groovy#L11-L53


After, it only remains to clean it up a bit and package it properly.

**Comment by KevinMenden** [comment]
That's great! I will try adding some tests sometime today :+1:

**Comment by pditommaso** [comment]
Closing as outdated
