### ISSUE TITLE
Validation Error when trying to run test 

### ISSUE THREAD

**Issue by Dane-Z** [nextflow-io/nf-validation#103]
Hi, I'm trying to implement the smrnaseq pipeline on an HPC but have been getting this error:

ERROR ~ a fault occurred in an unsafe memory access operation

Full terminal error:
nextflow run nf-core/smrnaseq -profile test,conda --outdir /gpfs/Cores/GSC/share/05_Scripts/nf-core
N E X T F L O W ~ version 23.04.3
Launching https://github.com/nf-core/smrnaseq [lonely_volhard] DSL2 - revision: https://github.com/nf-core/smrnaseq/commit/18d6c84926a3c983d4d9518a53020a7791746c98 [master]
ERROR ~ a fault occurred in an unsafe memory access operation

-- Check '.nextflow.log' file for details

nextflow version 23.04.03
HPC
Conda
Linux
[nextflow.log](https://github.com/nextflow-io/nf-validation/files/12769235/nextflow.log)

**Comment by nvnieuwk** [comment]
Hi @Dane-Z, have you tried deleting `~/.nextflow/plugins/nf-validation-*`. It could be a corrupted install. Sadly I can't know the real cause of the problem with the information you provided so anything more could be helpful if the problem persists.

**Comment by nvnieuwk** [comment]
Hi, awesome you were able to solve it that way! 

The conda error isn't an nf-validation error. I would post about it in the smrnaseq channel in the nf-core slack. They will be able to help you further :rocket:
