### ISSUE TITLE
YAML format samplesheets are not properly vaildated

### ISSUE THREAD

**Issue by awgymer** [nextflow-io/nf-validation#121]
Discovered as a side effect of #120 

`yaml` format samplesheets are currently not actually vaildated by the `validateFile`:

https://github.com/nextflow-io/nf-validation/blob/ac5812a4e3c4bd38fd60d40729f768faab03a1ea/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L188-L198

and

https://github.com/nextflow-io/nf-validation/blob/ac5812a4e3c4bd38fd60d40729f768faab03a1ea/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L416-L426

This doesn't throw an error but an empty list is passed to `validateFile` in the `yaml` case instead of the `fileContent`.

The fix should be as simple as switching to `fileContentCasted = new Yaml().load((samplesheetFile.text))`.

**Comment by mirpedrol** [comment]
Fixed by #124, thanks!
