### ISSUE TITLE
validateParameters raises warning when nextflow schema contains nested parameters

### ISSUE THREAD

**Issue by mattheww95** [nextflow-io/nf-validation#129]
This issue is likely tied to the others involving nested parameters but it is worth documenting. If a `nextflow_schema.json` file contains a group of nested parameters you will get a warning involving access to undefined parameters even if those parameters are initialized.

![image](https://github.com/nextflow-io/nf-validation/assets/76452933/34ae4d94-0640-4ad4-bd19-1131edb5ae9f)
 
A minimal example of this issue can be found here: https://github.com/mattheww95/bug_report

**Comment by nvnieuwk** [comment]
Hi @mattheww95 

Thanks for reporting this! Nested parameters currently are not supported by the plugin. We plan on adding this in the future though.
