### ISSUE TITLE
nf-validation fails when number parameters are set to 0

### ISSUE THREAD

**Issue by WackerO** [nextflow-io/nf-validation#137]
Hello, in https://github.com/nf-core/differentialabundance, I noticed that setting the following parameter:

```
"filtering_min_abundance": {
                    "type": "number",
                    "default": 1,
                    "description": "Minimum abundance value",
                    "fa_icon": "fas fa-compress-alt"
                }
```
to 0 will throw this error:
```
ERROR ~ ERROR: Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
The following invalid input values have been detected:

* Missing required parameter: --filtering_min_abundance
```
The problem is also not solved by setting 0.0; zero will not be recognized as a valid number.

It can easily be reproduced with e.g. the following command:
`nextflow run nf-core/differentialabundance -profile docker,test --outdir test_zero --filtering_min_abundance 0`

**Comment by nvnieuwk** [comment]
I guess this is caused by some invalid assertion (since `0` is the same as `false` in Groovy). I'd need to investigate further if I have some time. 
Can you try a quoted number in the meantime? (`--filtering_min_abundance "0"`)

**Comment by awgymer** [comment]
Issue occurs when we clean the parameters object. We strip out all the "false-y" values. Not sure why we are doing this so not sure if this affects other things? 

https://github.com/nextflow-io/nf-validation/blob/bcb92d81830f4b5773422382fbbe5c028fb4690a/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L1025-L1031

Solution may be as simple as changing the line to:
```
if (!p['value'] && p != 0)
```
