### ISSUE TITLE
Use standard JSON schema syntax for `dependentRequried`

### ISSUE THREAD

**Issue by mirpedrol** [nextflow-io/nf-validation#140]
In our sample sheet schema we write:
```json
"sample": {
    "dependentRequired": ["fastq_1"]
}
```
While standard JSON schema is:
```json
"dependentRequired": {
    "sample": ["fastq_1"]
 }
```
We should stick to the standard syntax.

**Comment by nvnieuwk** [comment]
Good idea, maybe while we're at it, we should change the JSON schema validator library to a newer one (https://github.com/networknt/json-schema-validator) so we support all newer versions of JSON schemas too

**Comment by nvnieuwk** [comment]
Added in version 2.0.0 :partying_face:
