### ISSUE TITLE
The link in the readme is broken 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nf-validation#145]
When open the link `https://nextflow-io.github.io/nf-validation` this page is displayed 

<img width="1563" alt="Screenshot 2024-01-18 at 16 41 23" src="https://github.com/nextflow-io/nf-validation/assets/816968/842af031-6aa9-4785-910c-5ca27061094a">

**Comment by mirpedrol** [comment]
It looks like this is due to `nextflow-io` being too similar to the real web `nextflow.io`. There seems to be a way to ask Google to not show this warning https://chromium.googlesource.com/chromium/src/+/6b68d1e9b4fec5a7ded58c4ba0fd08078c740c70/docs/security/lookalikes/lookalike-domains.md#appealing-a-lookalike-warning but we will need to proof ownership of `nextflow.io`. I guess someone from Seqera will have to do this (ping @ewels for visibility).

PS: The same issue happens with the docs in nf-co2footprint https://nextflow-io.github.io/nf-co2footprint/co2footprint/

**Comment by ewels** [comment]
Yeah I've seen this on a bunch of the github.io pages recently. It's very annoying. I'll take a look at the link 👍🏻

**Comment by ewels** [comment]
Reported here: https://crbug.com/1520276

🤞🏻

**Comment by ewels** [comment]
Ok I did it wrong:

> Thank you for the report. Based on the information you provided, you are eligible to use our automated process. However you have requested a manual review.
> 
> Before requesting manual review, please try to use the automated process. By using that process, your removal request is much less likely to be denied, and a approval is likely to happen more quickly. You can learn how to use the automated process at: https://g.co/chrome/lookalike-warnings#automated-warning-removal .
> 
> If you are unable to use the automated process, please re-request a manual review and explain why you are not able to use that process.

**Comment by ewels** [comment]
ok, I've opened a new PR on the nextflow.io website (https://github.com/nextflow-io/website/pull/165) to address this. As the GitHub pages websites are all hosted on sub-paths of the nexxtflow-io.github.io domain, I have created a new repo called [nextflow-io/.well-known](https://github.com/nextflow-io/.well-known) to mimic the expected path. If this works, it should hopefully prevent these warnings on _all_ GitHub pages mini sites (all plugins, plus the patterns website etc).

**Comment by ewels** [comment]
Leaving open until we have some idea as to whether it's worked or not..

**Comment by ewels** [comment]
Both asset link URLs are now live:
* https://nextflow.io/.well-known/assetlinks.json
* https://nextflow-io.github.io/.well-known/assetlinks.json

**Comment by ewels** [comment]
Got an email response:

<blockquote>

Thank you for submitting your submission. We have successfully fetched and processed your digital asset link manifests across the following domains:
  * [nextflow-io.github.io](https://www.google.com/url?q=http://nextflow-io.github.io&sa=D&source=buganizer&usg=AOvVaw1DHTQ8XWKdcIB2lR5X31kl)
  * [nextflow.io](https://www.google.com/url?q=http://nextflow.io&sa=D&source=buganizer&usg=AOvVaw1b6z4I1kwDYK9YDb3VD9l_)

Within a few days, lookalike warnings should stop showing on these sites. If you're still seeing the warnings in 1 week, feel free to follow-up here.

</blockquote>

Closing now, can reopen if people are still seeing this in more than a few days' time.

**Comment by nvnieuwk** [comment]
The issue still isn't resolved for me :cry:

**Comment by ewels** [comment]
Yeah, me either. I've followed up on the bug tracker to ask for manual assistance.

**Comment by ewels** [comment]
ok, the bug tracker issue has now been set to solved. Hopefully it's now fixed?

Seems to be working for me, can anyone else verify?

**Comment by pditommaso** [comment]
<img src="https://media1.giphy.com/media/oOCbcGBJjlXJL8imGO/giphy.gif"/>

**Comment by ewels** [comment]
Hooray! Thanks all 🥳

**Comment by pditommaso** [comment]
Thank Phil, you are a star

**Comment by nvnieuwk** [comment]
Seems to be working for me too, thanks Phil!
