### ISSUE TITLE
AWS Healthomics doesn't recognise this plugin

### ISSUE THREAD

**Issue by linminhtoo** [nextflow-io/nf-validation#147]
Hi,  i'm trying to run this gwas workflow https://github.com/genepi/nf-gwas by porting it into AWS Healthomics and running it on some test data. guide: https://catalog.us-east-1.prod.workshops.aws/workshops/76d4a4ff-fe6f-436a-a1c2-f7ce44bc5d17/en-US/workshop/create-healthomics-workflow 

However, I am getting this error from AWS:
```
Jan-24 08:42:55.367 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.exception.IllegalModulePath: Module path must start with / or ./ prefix -- Offending module: plugin/nf-validation 
```
it can't seem to fetch the plugin, which was specified here:
https://github.com/genepi/nf-gwas/blob/606ffe88f325de77fcdc799b8b090238920febc5/nextflow.config#L171
  & used here: 
https://github.com/genepi/nf-gwas/blob/606ffe88f325de77fcdc799b8b090238920febc5/main.nf#L13

what gives? is there a way for me to add this plugin into my git repository and import it locally then? 

thanks

**Comment by nvnieuwk** [comment]
Hi my best guess is that you are using an outdated version of Nextflow. Can you try updating to the latest stable version?

**Comment by linminhtoo** [comment]
> Hi my best guess is that you are using an outdated version of Nextflow. Can you try updating to the latest stable version?

Thanks a lot for your fast reply

i see, unfortunately AWS Healthomics only supports 22.04.0, so I have to use that version only. However it isn't too far behind what was specified in the original github repo (22.10.4)

**Comment by nvnieuwk** [comment]
The official lowest version that nf-validation is sure to work in is `22.10.0` anyways. I'm not sure I can do much for earlier versions :/

Maybe someone in the main nextflow repository will now of a workaround if you can't update the current nextflow version
