### ISSUE TITLE
Plugin with id nf-validation not found in any repository,What other ways can I install it? Can I directly download the binary file and use it?

### ISSUE THREAD

**Issue by xfk274280** [nextflow-io/nf-validation#173]
(env_nf) [nf_core]$ nextflow run nf-core-circrna_dev/dev --input samplecircrna.csv --phenotype samplecircrna_condition.csv  --outdir testout
N E X T F L O W  ~  version 23.10.1
Launching `nf-core-circrna_dev/dev/main.nf` [wise_mahavira] DSL2 - revision: 1bbcf15e63
Downloading plugin nf-validation@1.1.3
ERROR ~ Plugin with id nf-validation not found in any repository

 -- Check '.nextflow.log' file for details
(env_nf) [ nf_core]$ nextflow plugin install nf-validation
ERROR ~ Cannot find latest version of nf-validation plugin

**Comment by mirpedrol** [comment]
Hi @xfk274280, [here](https://www.nextflow.io/docs/latest/plugins.html#offline-usage) you can find instructions on how to use the downloaded plugin

**Comment by xfk274280** [comment]
> Hi @xfk274280, [here](https://www.nextflow.io/docs/latest/plugins.html#offline-usage) you can find instructions on how to use the downloaded plugin

Thank you for your help. I've seen this place before, but I just know how to use it now.
