### ISSUE TITLE
Example in the QuickStart section has a syntax error

### ISSUE THREAD

**Issue by tfenne** [nextflow-io/nf-validation#23]
I copy/pasted the example in the quick start to get up and running, and immediately got a NF error on the `include` line.  Editing it to use semi-colons instead of commas, as follows, worked for me:

```
include { validateParameters; paramsHelp; paramsSummaryMap; paramsSummaryLog; validateAndConvertSamplesheet } from 'plugin/nf-validation'
```

**Comment by nvnieuwk** [comment]
Thank you! I'll make a quick PR to fix this :)

**Comment by nvnieuwk** [comment]
Hi @tfenne the README has been adjusted.
