### ISSUE TITLE
Is this an official plugin, yet?

### ISSUE THREAD

**Issue by mmatthews06** [nextflow-io/nf-validation#4]
@pditommaso , or anyone else, is this going to be an official plugin at some point? If it already is, are the instructions for using it from just the `nextflow` command? I don't see this plugin in the list, here:
https://github.com/nextflow-io/plugins/blob/main/plugins.json

I could try to make a docs submission if this is officially supported, and I get a little direction.

**Comment by ewels** [comment]
Not yet - it went stale when the guy working on it got a new job. We're hoping to hire some new developers for nf-core in the new year and this plugin will be one of the things that they work on.

**Comment by nvnieuwk** [comment]
Hi @mmatthews06. this plugin has now been released as version `0.1.0`
