### ISSUE TITLE
Any chance of making release notes on GitHub for recent (and future) releases?

### ISSUE THREAD

**Issue by tfenne** [nextflow-io/nf-validation#53]
I, and I'm sure others, would greatly appreciate release notes with official releases of the plugin.  Given the policy/practice of merging PRs without squashing it is _really_ hard for an outsider to look through the commit history and see what's changed between versions.

Or a CHANGELOG.md or a section in the README.

**Comment by nvnieuwk** [comment]
Hi @tfenne, thank you for making this issue this does indeed make a lot of sense to add! We'll look into it

**Comment by nvnieuwk** [comment]
A changelog has been added in `CHANGELOG.md` and to the releases :)
