### ISSUE TITLE
Is there a way to express in the schema that a file-path is required, but the path it points to is allowed to not exist?

### ISSUE THREAD

**Issue by tfenne** [nextflow-io/nf-validation#57]
As best I can tell, when specifying an input in my schema as a `file-path` or `directory-path`, the plugin will validate that any path given already exists.  Is there a way to specify for a given parameter that the target may not exist?

Note that this is different than required/not-required.  This comes up mostly for output paths, where the path may not exist yet and the pipeline is expected to create it.

**Comment by mirpedrol** [comment]
Hi @tfenne,
A new JSON schema key [`exists`](https://nextflow-io.github.io/nf-validation/nextflow_schema/nextflow_schema_specification/#exists) was added in version 0.2.0 to address this. Now, providing a format `file-path` or `directory-path` should only check that the values are paths, and only if the key `exists` is set to true we check the existence.

**Comment by tfenne** [comment]
Thanks!  Are the docs new?  I hadn't seen those before, but they look great.
