### ISSUE TITLE
Samplesheet fields that are not defined in samplesheet schema should be silently ignored

### ISSUE THREAD

**Issue by koenbossers** [nextflow-io/nf-validation#58]
### Problem

When using `Channel.fromSamplesheet` , I get warnings when there are fields present in a samplesheet that are not defined in the associated json schema:

```
WARN: Unable to cast value dummy_flowcell to type null: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "type" is null
WARN: Unable to cast value BC01 to type null: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "type" is null
```

My understanding is that these undefined fields should be silently ignored

### Versions:
- `nf-validation@0.2.1`
- Nextflow: `23.04.1`

### Input & schema definitions

Samplesheet: https://raw.githubusercontent.com/koenbossers/testdata/main/nextflow_precisionfoodsafety/test_samplesheet_minimal.csv

The fields `barcode_short` and `flowcell_id_short` are not defined, and those values trigger the warnings. 

Relevant section of `nextflow_schema.json`
```
    "definitions": {
        "input_output_options": {
            "title": "Input/output options",
            "type": "object",
            "fa_icon": "fas fa-terminal",
            "description": "Define where the pipeline should find input data and save output data.",
            "required": ["input", "outdir"],
            "properties": {
                "input": {
                    "type": "string",
                    "format": "file-path",
                    "mimetype": "text/csv",
                    "pattern": "^\\S+\\.csv$",
                    "schema": "assets/schema_input.json",
                    "description": "Path to comma-separated file containing information about the samples in the experiment.",
                    "help_text": "You will need to create a design file with information about the samples in your experiment before running the pipeline. Use this parameter to specify its location. It has to be a comma-separated file with 3 columns, and a header row.",
                    "fa_icon": "fas fa-file-csv",
                    "exists": true
                },
```

Contents of `assets/schema_input.json`
```
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/lcab/precisionfoodsafety/master/assets/schema_input.json",
    "title": "lcab/precisionfoodsafety pipeline - params.input schema",
    "description": "Schema for the file provided with params.input",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "sample": {
                "type": "string",
                "pattern": "^\\S+$",
                "errorMessage": "Sample name must be provided and cannot contain spaces",
                "meta": ["sample_id"],
                "unique": ["flowcell_id", "barcode"]
            },
            "flowcell_id": {
                "type": "string",
                "pattern": "^\\S+$",
                "errorMessage": "Sample name must be provided and cannot contain spaces",
                "meta": ["flowcell_id"]
            },
            "barcode": {
                "type": "string",
                "pattern": "^barcode[0-9][0-9]",
                "errorMessage": "Must be provided and of form 'barcode[00..99]",
                "meta": ["barcode"]
            },
            "location": {
                "anyOf": [
                    {
                        "type": "string",
                        "format": "directory-path",
                        "exists": true
                    },
                    {
                        "type": "string",
                        "format": "file-path",
                        "exists": true,
                        "pattern": "^\\S+\\.f(ast)?q[\\.gz]{0,}$"
                    }
                ]
            }
        },
        "required": ["sample", "flowcell_id", "barcode", "location"]
    }
}

```

**Comment by mirpedrol** [comment]
Yes! We should capture this values which are not in the schema and avoid having these kind of confusing errors. 
For pipeline parameters we throw a warning whenever we find a parammeter which is not in the shcema, and we also have a parameter [---validationSchemaIgnoreParams](https://nextflow-io.github.io/nf-validation/parameters/validation/#ignoring-unrecognized-parameters) to ignore these warnings. We could implement a similar logic for the samplesheet.

**Comment by koenbossers** [comment]
Just out of curiosity (I have no experience in coding in Groovy, so please feel free to ignore this comment if totally incorrect 🥲  ) I went out to have a look where in the sourcecode this issue is coming from. May have found the issue.


https://github.com/nextflow-io/nf-validation/blob/534cf9159a37a240c3d502a6488ae62f670c588c/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L435-L463


If in line 466 an extra check is performed if `type == null` i suspect that the issue will be solved.

```groovy
                 if( str == null || str == ''  || type == null) castedRow[key] = null 
```

**Comment by mirpedrol** [comment]
Hi @koenbossers,

I was having another look at this, trying to reproduce the warnings and I see that we already have a warning informing that some fields are not present in the schema, which is what I was suggesting in my previous comment.
```
WARN: Samplesheet warnings:
        The samplesheet contains following unchecked field(s): [extra_field_2, extra_field]
```

To avoid the other warnings about casting, your solutions seem like a good approach :) Do you fancy opening a PR adding this new `else if`?
