### ISSUE TITLE
Feature request: allow quotes strings containing commas in .fromSamplesheet() for .csv files

### ISSUE THREAD

**Issue by koenbossers** [nextflow-io/nf-validation#62]
At this moment, it is not possible to create a channel from a `.csv` file with the `.fromSamplesheet()` function if the `.csv` file contains a quoted field that contains a comma.

```csv
id,path,description
sample1,reads.sample1.fq.gz,"no problems here"
sample2,reads.sample2.fq.gz,"oh no, I cause issues"
```

The line in row 2 will be split on the `no,` as well, which is not the desired behavior.

It should be easy to add this functionality by adding the appropriate parameter value ` quote:true` (https://www.nextflow.io/docs/latest/operator.html#splitcsv) to the following line:

https://github.com/nextflow-io/nf-validation/blob/b040ebbddf55163f61b8a0c22f49d5450146519b/plugins/nf-validation/src/main/nextflow/validation/SamplesheetConverter.groovy#L75

But perhaps it is even a good idea to allow all `.splitCsv` parameters to be passed through as well?

**Comment by nvnieuwk** [comment]
Hi @koenbossers thank you again for the great issue! Can you open up a PR to add this?
