### ISSUE TITLE
Default to report an error if the rows in a sample sheet are not unique

### ISSUE THREAD

**Issue by mirpedrol** [nextflow-io/nf-validation#70]
Processing the same sample twice is usually not desired. We should add a new functionality which throws an error if rows in a sample sheet are not unique.
Add a new flag to disable this behaviour.
A sample sheet can contain additional entries which are ignored if they aren't present in the JSON schema. We should also ignore them and apply the `unique` only for the combination of all entries present in the schema.

**Comment by nvnieuwk** [comment]
That is already implemented (https://nextflow-io.github.io/nf-validation/nextflow_schema/sample_sheet_schema_specification/#unique) or do you mean something else? I can have a look at that if you can clarify it a bit more :)

**Comment by mirpedrol** [comment]
The idea is to do the same as we can do with `unique` specifying all column names, but to add this as a default. 
This issue comes from [this](https://nfcore.slack.com/archives/C05785S3TMX/p1688722870945639) slack discussion

**Comment by nvnieuwk** [comment]
Aaah I get it! Yes this would be a great idea! So basically we want to have a check to see if all rows have at least one difference in them. If there are fully duplicate rows in the samplesheet we should throw an error?

**Comment by mirpedrol** [comment]
exactly :) 
And add a new argument to disable this if needed

**Comment by nvnieuwk** [comment]
Allright, I'll have a go at it later today :)

**Comment by mirpedrol** [comment]
great, thanks!
