### ISSUE TITLE
Add a link to the slack channel in the docs

### ISSUE THREAD

**Issue by nvnieuwk** [nextflow-io/nf-validation#75]
I think the docs would really benefit from a link to the Slack channel

**Comment by lukbut** [comment]
Hey @nvnieuwk which Slack channel specifically? The nf-core one or is there a dedicated nf-validation one?

**Comment by nvnieuwk** [comment]
There is dedicated `nf-validation` Slack channel called #nf-validation

**Comment by nvnieuwk** [comment]
Thanks for taking a look at this!

**Comment by lukbut** [comment]
I'm working on this issue
