### ISSUE TITLE
AWS error when iGenomes path is defined

### ISSUE THREAD

**Issue by matthdsm** [nextflow-io/nf-validation#92]
Hi,

I'm getting the following error when a default iGenomes S3 path is defined:
```
ERROR ~ The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 73HW8YCDVSYJPDES; S3 Extended Request ID: 4USexpHHlbBBFqNCoadx9LEGKuMBhWsUfrdZFAZUaYVnC3bPDGWfoC8EaEY82Cr70hlgxjc9xrs=; Proxy: null)
```

I suppose this has something to do with the plugin trying to stage the data before all configs are loaded or something.

Have you encountered this before and what was the solution?
I tested this on a newly generated workflow.

Cheers
Matthias

**Comment by nvnieuwk** [comment]
Thanks for reporting!

This is a known issue and a fix has been implemented in `nf-core` tools (https://github.com/nf-core/tools/pull/2419). I'm not sure we can do much about this from our end, but could be worth having a look at.

**Comment by nvnieuwk** [comment]
So basically, you can just ignore this (it won't affect the validation that much because all files in the igenomes path will be validated anyways)

**Comment by ewels** [comment]
Merged into the nf-core template. I think that there's nothing to do here.

If this keeps coming up in other situations (unused parameters mentioning s3 paths which will never be used), then we can revisit and perhaps look into handling those Nextflow exceptions / errors.
